---
- hosts: '{{ hosts  }}'
  remote_user: root
  tasks: 
      - name: Install Package ClamAV   (CentOS 5 , CentOS 6)
        yum: state=latest name={{item}}
        with_items:
         - clamav 
         - clamd
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version <= '6'
      
      - name: Install Package ClamAV (CentOS 7)
        yum: state=latest name={{item}}
        with_items:
         - clamav-server 
         - clamav-data 
         - clamav-update 
         - clamav-filesystem 
         - clamav 
         - clamav-scanner-systemd 
         - clamav-devel
         - clamav-lib
         - clamav-server-systemd 
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'

      - name: Install Package Spacewalk Clien for ubuntu
        apt: name={{item}} state=present update_cache=yes
        with_items:
          - clamav
          - clamav-daemon
        when: ansible_distribution == "Ubuntu" 

      - name: Config ClamAV  (CentOS 6)
        lineinfile: dest=/etc/clamd.conf regexp="{{ item.regexp }}" insertbefore="{{ item.insertbefore }}" line="{{ item.line }}" state=present backup=yes
        with_items:
          - { regexp: '^TCPSocket', insertbefore: '^#TCPSocket' , line: 'TCPSocket 3310'}
          - { regexp: '^Example', insertbefore: '^Example' , line: '#Example'}
          - { regexp: '^LocalSocket', insertbefore: '^#LocalSocket' , line: 'LocalSocket /var/run/clamav/clamd.sock'}
          - { regexp: '^DatabaseDirectory', insertbefore: '^#DatabaseDirectory' , line: 'DatabaseDirectory /var/lib/clamav'} 
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '6'

      - name: Config ClamAV  (CentOS 7)
        lineinfile: dest=/etc/clamd.d/scan.conf regexp="{{ item.regexp }}" insertbefore="{{ item.insertbefore }}" line="{{ item.line }}" state=present backup=yes
        with_items:
          - { regexp: '^Example', insertbefore: '^Example' , line: '#Example'}
<<<<<<< HEAD
          - { regexp: '^LocalSocket', insertbefore: '^#LocalSocket' , line: 'LocalSocket /var/clamav/clamd.socket'}
=======
          - { regexp: '^LocalSocket', insertbefore: '^#LocalSocket' , line: 'LocalSocket /var/run/clamav/clamd.sock'}
>>>>>>> 5ba2fe77777d4e33a11b32f1832af5966031c489
          - { regexp: '^DatabaseDirectory', insertbefore: '^#DatabaseDirectory' , line: 'DatabaseDirectory /var/lib/clamav'} 
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'

      - name: Config freshclam 
        lineinfile: dest=/etc/freshclam.conf regexp="{{ item.regexp }}" insertbefore="{{ item.insertbefore }}" line="{{ item.line }}" state=present backup=yes
        with_items:
          - { regexp: '^Example', insertbefore: '^Example' , line: '#Example'}
          - { regexp: '^DatabaseDirectory', insertbefore: '^#DatabaseDirectory' , line: 'DatabaseDirectory /var/lib/clamav'} 
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7' and ansible_distribution_major_version == '6'

      - name: Cleanup Config ClamAV (CentOS 6)
        lineinfile: dest=/etc/clamd.conf regexp="{{ item.regexp }}"  state=absent
        with_items:
          - { regexp: '^#Example'}
          - { regexp: '^#LocalSocket'}
          - { regexp: '^#DatabaseDirectory'}
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '6'

      - name: Cleanup Config ClamAV (CentOS 7)
        lineinfile: dest=/etc/clamd.d/scan.conf regexp="{{ item.regexp }}"  state=absent
        with_items:
          - { regexp: '^#Example'}
          - { regexp: '^#LocalSocket'}
          - { regexp: '^#DatabaseDirectory'}
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'

      - name: mkdir log path ClamAV
        file: path="{{ item.path }}"  state=directory mode="0744" recurse=yes owner=clam 
        with_items:
          - { path: '/var/log/clamav/scan_hourly/'}
          - { path: '/var/log/clamav/scan_daily/'}
<<<<<<< HEAD
          - { path: '/var/clamav/'}
=======
          - { path: '/var/run/clamav'}
>>>>>>> 5ba2fe77777d4e33a11b32f1832af5966031c489
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '6'

      - name: mkdir log path ClamAV
        file: path="{{ item.path }}"  state=directory mode="0744" recurse=yes owner=clamscan 
        with_items:
          - { path: '/var/log/clamav/scan_hourly/'}
          - { path: '/var/log/clamav/scan_daily/'}
<<<<<<< HEAD
          - { path: '/var/clamav/'}
=======
          - { path: '/var/run/clamav'}
>>>>>>> 5ba2fe77777d4e33a11b32f1832af5966031c489
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'

      - name: Install Config schedule scan clamav 
        copy: src='{{ item.src }}' dest='{{ item.dest }}' mode="0755"
        with_items:
          - { src: './template/logrotate_clamav' , dest: '/etc/logrotate.d/clamav' }
          - { src: './template/clamscan_daily' , dest: '/etc/cron.daily/clamav_daily' }
          - { src: './template/clamscan_hourly' , dest: '/etc/cron.hourly/clamav_hourly' }

      - name: Update database ClamAV
        shell: freshclam

      - name: Install Config freshclam systemd 
        copy: src='{{ item.src }}' dest='{{ item.dest }}' mode="0644" owner=root group=root
        with_items:
          - { src: './template/freshclam.service' , dest: '/usr/lib/systemd/system/freshclam.service' }
        when: ansible_distribution == "CentOS"  and ansible_distribution_major_version == '7'

      - name: restart clamd [CentOS 5, CentOS 6 ,Ubuntu 12 , Ubuntu 14 ]
        service: state=started name=clamd enabled=yes
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version <= '6' or ansible_distribution == "Ubuntu" and ansible_distribution_major_version <= '14'

      - name: restart clamd [CentOS 7 or Ubuntu 16.04]
        shell: systemctl restart freshclam clamd@scan
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'
